sudo: required
language: c
compiler:
- gcc
services:
- docker
script:
- docker build . --tag jhpoelen/taxonworks-dev:latest
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker images
- docker push jhpoelen/taxonworks-dev:latest
