sudo: required
language: c
compiler:
- gcc
services:
- docker
script:
- docker build
- echo "$DOCKER_PASSWORD" > docker login -u "$DOCKER_USERNAME" --password-stdin
- docker images
- docker tag taxonworks_app:latest jhpoelen/taxonworks:dev
- docker push jhpoelen/taxonworks:dev
